#if UNITY_EDITOR

using System.IO;
using UnityEngine;
using UnityEditor;

namespace RAXY.Utility
{
    /// <summary>
    /// Installs a git pre-commit hook to prevent accidental commit of local manifest paths
    /// </summary>
    public static class GitHookInstaller
    {
        private const string HOOK_CONTENT = @"#!/bin/sh
# Auto-generated by RAXY.Utility ManifestSwitcher
# Prevents committing manifest.json with local file paths

MANIFEST_FILE=""Packages/manifest.json""

if [ -f ""$MANIFEST_FILE"" ]; then
    if grep -q '""file:' ""$MANIFEST_FILE""; then
        echo ""ERROR: manifest.json contains local 'file:' paths""
        echo ""Run 'Switch to Remote' in ManifestSwitcher before committing.""
        echo ""Location: Assets -> RAXY -> Editor -> Manifest Switcher""
        exit 1
    fi
fi

exit 0
";

        [MenuItem("Tools/RAXY/Git Hooks/Install Pre-Commit Hook")]
        public static void InstallPreCommitHook()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string hooksDir = Path.Combine(projectRoot, ".git", "hooks");
            string hookPath = Path.Combine(hooksDir, "pre-commit");

            if (!Directory.Exists(Path.Combine(projectRoot, ".git")))
            {
                EditorUtility.DisplayDialog(
                    "Git Not Found",
                    "This project does not appear to be a git repository.\n\nInitialize git first with: git init",
                    "OK");
                return;
            }

            if (!Directory.Exists(hooksDir))
            {
                Directory.CreateDirectory(hooksDir);
            }

            if (File.Exists(hookPath))
            {
                bool overwrite = EditorUtility.DisplayDialog(
                    "Hook Already Exists",
                    "A pre-commit hook already exists. Overwrite it?",
                    "Overwrite",
                    "Cancel");

                if (!overwrite)
                    return;
            }

            try
            {
                File.WriteAllText(hookPath, HOOK_CONTENT);

                if (Application.platform == RuntimePlatform.OSXEditor ||
                    Application.platform == RuntimePlatform.LinuxEditor)
                {
                    System.Diagnostics.Process.Start("chmod", $"+x \"{hookPath}\"");
                }

                EditorUtility.DisplayDialog(
                    "Success",
                    "Pre-commit hook installed. Git will block commits when manifest.json has local paths.\n\n" +
                    $"Location: {hookPath}",
                    "OK");

                Debug.Log($"Git pre-commit hook installed at: {hookPath}");
            }
            catch (System.Exception ex)
            {
                EditorUtility.DisplayDialog(
                    "Error",
                    $"Failed to install hook:\n{ex.Message}",
                    "OK");
                Debug.LogError($"Failed to install pre-commit hook: {ex}");
            }
        }

        [MenuItem("Tools/RAXY/Git Hooks/Uninstall Pre-Commit Hook")]
        public static void UninstallPreCommitHook()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string hookPath = Path.Combine(projectRoot, ".git", "hooks", "pre-commit");

            if (!File.Exists(hookPath))
            {
                EditorUtility.DisplayDialog(
                    "Not Found",
                    "No pre-commit hook found to uninstall.",
                    "OK");
                return;
            }

            bool confirm = EditorUtility.DisplayDialog(
                "Confirm Uninstall",
                "Are you sure you want to remove the pre-commit hook?",
                "Yes, Remove",
                "Cancel");

            if (!confirm)
                return;

            try
            {
                File.Delete(hookPath);
                EditorUtility.DisplayDialog(
                    "Success",
                    "Pre-commit hook removed successfully.",
                    "OK");
                Debug.Log("Git pre-commit hook uninstalled.");
            }
            catch (System.Exception ex)
            {
                EditorUtility.DisplayDialog(
                    "Error",
                    $"Failed to remove hook:\n{ex.Message}",
                    "OK");
                Debug.LogError($"Failed to uninstall pre-commit hook: {ex}");
            }
        }

        [MenuItem("Tools/RAXY/Git Hooks/Test Pre-Commit Hook")]
        public static void TestPreCommitHook()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string hookPath = Path.Combine(projectRoot, ".git", "hooks", "pre-commit");

            if (!File.Exists(hookPath))
            {
                EditorUtility.DisplayDialog(
                    "Not Installed",
                    "Pre-commit hook is not installed.\n\nInstall it via: Tools -> RAXY -> Git Hooks -> Install Pre-Commit Hook",
                    "OK");
                return;
            }

            string manifestPath = Path.Combine(projectRoot, "Packages", "manifest.json");
            if (!File.Exists(manifestPath))
            {
                Debug.LogWarning("manifest.json not found");
                return;
            }

            string json = File.ReadAllText(manifestPath);
            bool hasLocalPaths = json.Contains("\"file:");

            if (hasLocalPaths)
            {
                EditorUtility.DisplayDialog(
                    "Test Result",
                    "Hook would BLOCK this commit. Manifest contains local file paths.",
                    "OK");
                Debug.LogWarning("Pre-commit hook test: would block commit (manifest has local paths)");
            }
            else
            {
                EditorUtility.DisplayDialog(
                    "Test Result",
                    "Hook would ALLOW this commit. Manifest is clean.",
                    "OK");
                Debug.Log("Pre-commit hook test: would allow commit (manifest is clean)");
            }
        }
    }
}

#endif
